name: Build
on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: release-asset-foo.txt
          path: release-asset-foo.txt
          if-no-files-found: error
          retention-days: 2
      - uses: actions/upload-artifact@v3
        with:
          name: release-asset-bar.txt
          path: release-asset-bar.txt
          if-no-files-found: error
          retention-days: 2
      - uses: actions/upload-artifact@v3
        with:
          name: non-release-artifact.txt
          path: non-release-artifact.txt
          if-no-files-found: error
          retention-days: 2

      - uses: actions/github-script@v6
        with:
          script: |
            // console.log('Context: ', context);
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                head_sha: context.sha,
                // May actually be a tag name.
                branch: process.env.GITHUB_REF_NAME,
            });
            // console.log('Runs.data.workflow_runs: ', runs.data.workflow_runs);
            const artifacts = [];

            for (const run of runs.data.workflow_runs) {
                console.log('Run: ', run);
                const runArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                    owner,
                    repo,
                    run_id: run.id,
                });
            
                for (const artifact in runArtifacts) {
                    console.log('Artifact: ', artifact);
                }
            }
