name: Release build
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# NOPE: https://api.github.com/repos/intgr/test-github-actions/actions/artifacts
# https://api.github.com/repos/intgr/test-github-actions/actions/workflows/35763544/runs?head_sha=fa997e209ab5a98af40731b61ae38f5c37685b30&branch=0.0.1
# https://api.github.com/repos/intgr/test-github-actions/actions/workflows/build.yml/runs?head_sha=fa997e209ab5a98af40731b61ae38f5c37685b30&branch=0.0.1
# https://api.github.com/repos/intgr/test-github-actions/actions/runs?head_sha=fa997e209ab5a98af40731b61ae38f5c37685b30&branch=0.0.1
# https://api.github.com/repos/intgr/test-github-actions/actions/runs/3122506296/artifacts

      - uses: actions/github-script@v6
        with:
          script: |
            // console.log('Context: ', context);
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                head_sha: context.sha,
                // May actually be a tag name.
                branch: process.env.GITHUB_REF_NAME,
            });
            // console.log('Runs.data.workflow_runs: ', runs.data.workflow_runs);
            const artifacts = [];

            for (const run of runs.data.workflow_runs) {
                console.log('Run: ', run);
                const runArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                    owner,
                    repo,
                    run_id: run.id,
                });
                
                console.log("Artifacts count: ", runArtifacts.data.total_count);
                console.log("Artifacts: ", runArtifacts.data.artifacts);
                for (const artifact of runArtifacts.data.artifacts) {
                    console.log('Artifact: ', artifact);
                }
            }

